spring.datasource.url=jdbc:h2:mem:vendasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=vendas_admin
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.swagger-ui.enabled=false

scalar.enabled=true
scalar.url=/v3/api-docs
scalar.path=/docs
scalar.theme=deepSpace